### ISSUE TITLE
Export action generates conflict with Mailpoet export action

### ISSUE THREAD

**Issue by emagma-marion** [dmassiani/wpcomponent#14]
Hi,
I installed Wpcomponent and Mailpoet on a website. When I try to export subscribers list on mailpoet, wpcomponent export action is loading.
There is no test on the current page in the export action which generates a conflict with the export action of Mailpoet.
Thanks for your feedback

**Comment by dmassiani** [comment]
Ok, I investigate.

**Comment by dmassiani** [comment]
Fixed in 2.1.6
